/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lexso.sales;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.lexso.connection.DatabaseConnection;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NGD NISSHANKA
 */
public class SalesAnalysis extends javax.swing.JFrame {

//    private Home home;
    /**
     * Creates new form SalesAnalysis
     */
    public SalesAnalysis() {
        initComponents();
        loadInvoiceList();
    }

     private void loadInvoiceList() {
        loadInvoiceList(""); // Call with empty search by default
    }
     
     private void loadInvoiceList(String searchText) {
        try {
            String query = "SELECT invoice.id, invoice.user_email, "
                    + "CONCAT(customer.First_name, ' ', customer.Last_name) AS customer_name, "
                    + "invoice.customer_mobile, SUM(invoice_item.qty) AS total_qty, "
                    + "invoice.paid_amount, invoice.discount, invoice.payment_status, invoice.date "
                    + "FROM invoice_item "
                    + "INNER JOIN invoice ON invoice_item.invoice_id = invoice.id "
                    + "LEFT JOIN customer ON invoice.customer_mobile = customer.mobile ";

            // Add WHERE clause if search text is provided
            if (!searchText.isEmpty()) {
                query += "WHERE invoice.id LIKE '%" + searchText + "%' "
                        + "OR invoice.user_email LIKE '%" + searchText + "%' "
                        + "OR invoice.customer_mobile LIKE '%" + searchText + "%' "
                        + "OR invoice.date LIKE '%" + searchText + "%' "
                        + "OR CONCAT(customer.First_name, ' ', customer.Last_name) LIKE '%" + searchText + "%' "
                        + "OR customer.First_name LIKE '%" + searchText + "%' "
                        + "OR customer.Last_name LIKE '%" + searchText + "%'";
            }

            query += " GROUP BY invoice.id, invoice.user_email, customer_name, invoice.customer_mobile, "
                    + "invoice.paid_amount, invoice.discount, invoice.payment_status, invoice.date";

            ResultSet resultSet = DatabaseConnection.executeSearch(query);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("id")); // Invoice ID
                vector.add(resultSet.getString("user_email")); // Employee Email
                vector.add(resultSet.getString("customer_name")); // Customer Full Name
                vector.add(resultSet.getString("customer_mobile")); // Customer Mobile
                vector.add(resultSet.getString("total_qty")); // Total Items
                vector.add(resultSet.getString("discount")); // Total Discount
                vector.add(resultSet.getString("paid_amount")); // Total Amount
                vector.add(resultSet.getString("payment_status")); // Status
                vector.add(resultSet.getString("date")); // Date & Time
                model.addRow(vector);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading invoice data: " + e.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Search");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Invoice ID", "Employee Email", "Customer Name", "Customer Mobile", "Total Items", "Total Discount", "Total Amount", "Status", "Date & Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Invoices List");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 538, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        String searchText = jTextField2.getText().trim();
        loadInvoiceList(searchText); // Reload with search filter
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // invoiceitems open
        // invoiceitems open
        int row = jTable1.getSelectedRow();
        if (row >= 0) { // Check if a valid row is selected
            String invID = String.valueOf(jTable1.getValueAt(row, 0));
            String empEmail = String.valueOf(jTable1.getValueAt(row, 1));
            String cusName = String.valueOf(jTable1.getValueAt(row, 2));
            String cusMobile = String.valueOf(jTable1.getValueAt(row, 3));
            String status = String.valueOf(jTable1.getValueAt(row, 7)); // Payment status is at index 7
            String dateTime = String.valueOf(jTable1.getValueAt(row, 8)); // DateTime is at index 8

            if (evt.getClickCount() == 2) {
                // invoice item dialog open
                System.out.println("invoice items Button Clicked");
                invoiceItems invitemPanel = new invoiceItems();

                // Set the values in the invoiceItems panel
                invitemPanel.setInvoiceID(invID);
                invitemPanel.setEmployeeEmail(empEmail);
                invitemPanel.setCustomerName(cusName);
                invitemPanel.setCustomerMobile(cusMobile);
                invitemPanel.setPaymentStatus(status);
                invitemPanel.setDateTime(dateTime);

                JDialog frame = new JDialog(this, true);
                frame.add(invitemPanel);
                frame.setSize(1105, 710);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesAnalysis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
