/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.lexso.users.bankaccounts;

import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import com.lexso.connection.DatabaseConnection;

/**
 *
 * @author User
 */
public class AddOrUpdateBankAC extends javax.swing.JDialog {

    private static HashMap<String, String> bankMap = new HashMap<>();

    private AllBankAccountsWindow parentFrame;
    private static String recent;

    /**
     * Creates new form AddOrUpdateBankAC
     */
    public AddOrUpdateBankAC(java.awt.Frame parent, boolean modal, String recent) {
        super(parent, modal);
        initComponents();
        this.recent = recent;
        this.parentFrame = (AllBankAccountsWindow) parent;
        loadBank();
        loadEmployeeEmail();

        if (recent.equals("update")) {
            addButton.setVisible(false);
            addmoreButton.setVisible(false);
            updateButton.setVisible(true);
            cancelButton.setVisible(true);
        } else if (recent.equals("view")) {
            addButton.setVisible(false);
            addmoreButton.setVisible(false);
            updateButton.setVisible(false);
            cancelButton.setVisible(true);

            emailComboBox.setEditable(false);
            bankComboBox.setEditable(false);
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            jTextField3.setEditable(false);
            jTextArea1.setEditable(false);
        } else {
            addButton.setVisible(true);
            addmoreButton.setVisible(true);
            updateButton.setVisible(false);
            cancelButton.setVisible(true);
        }

        checkBankDetails(recent);
    }

    public void setTitle(String title) {
        jLabel1.setText(title);
    }

    public void setEmail(String email) {
        emailComboBox.setSelectedItem(email);
    }

    public void setBankName(String bank) {
        bankComboBox.setSelectedItem(bank);
    }

    public void setACHolderName(String name) {
        jTextField1.setText(name);
    }

    public void setACNumber(String ac) {
        jTextField2.setText(ac);
    }

    public void setBranch(String branch) {
        jTextField3.setText(branch);
    }

    public void setDescription(String desc) {
        jTextArea1.setText(desc);
    }

    private void loadBank() {

        try {

            ResultSet resultSet = DatabaseConnection.executeSearch("SELECT * FROM `bank`");

            Vector vector = new Vector();

            while (resultSet.next()) {
                vector.add(resultSet.getString("bank_name"));
                bankMap.put(resultSet.getString("bank_name"), resultSet.getString("id"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
            bankComboBox.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void loadEmployeeEmail() {

        try {

            ResultSet resultSet = DatabaseConnection.executeSearch("SELECT * FROM `employee`");

            Vector vector = new Vector();

            while (resultSet.next()) {
                vector.add(resultSet.getString("email"));
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(vector);
            emailComboBox.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        bankComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        addmoreButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("View Bank Account");

        jLabel2.setForeground(new java.awt.Color(0, 51, 0));
        jLabel2.setText("Keep Bank Account Details Up to Date!");

        jLabel3.setText("email");

        emailComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        emailComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                emailComboBoxItemStateChanged(evt);
            }
        });

        jLabel4.setText("Bank Name");

        bankComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("AC Holder Name");

        jLabel6.setText("Account Number");

        jLabel7.setText("Branch");

        jLabel8.setText("Description");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(204, 204, 0));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(0, 204, 0));
        addButton.setText("Save & Exit");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        addmoreButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addmoreButton.setForeground(new java.awt.Color(0, 204, 204));
        addmoreButton.setText("Save & Add More");
        addmoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 7, Short.MAX_VALUE)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addmoreButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 220, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bankComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addmoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addOrUpdateBankDetails();
        parentFrame.loadBankData("");
        this.dispose();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        addOrUpdateBankDetails();

        parentFrame.loadBankData("");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void addmoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmoreButtonActionPerformed
        addOrUpdateBankDetails();
        parentFrame.loadBankData("");
    }//GEN-LAST:event_addmoreButtonActionPerformed

    private void emailComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_emailComboBoxItemStateChanged
        checkBankDetails(recent);
    }//GEN-LAST:event_emailComboBoxItemStateChanged

    private void addOrUpdateBankDetails() {

        try {
            ResultSet bankresultSet = DatabaseConnection.executeSearch("SELECT * FROM `bank_details` "
                    + "INNER JOIN `bank` ON `bank_details`.`bank_id` = `bank`.`id` "
                    + "WHERE `bank_details`.`employee_email` = '" + emailComboBox.getSelectedItem() + "'");

            String name = jTextField1.getText();
            String acnumber = jTextField2.getText();
            String branch = jTextField3.getText();
            String description = jTextArea1.getText();

            String bank_name = String.valueOf(bankComboBox.getSelectedItem());

            if (name.isEmpty() || acnumber.isEmpty() || branch.isEmpty() || description.isEmpty() || bank_name == null) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields.");
                return;
            }

            if (!bankresultSet.next()) {
                DatabaseConnection.executeIUD("INSERT INTO `bank_details`(`name`, `acnumber`, `branch`, `description`, `bank_id`, `employee_email`) VALUES ('" + name + "', '" + acnumber + "', '" + branch + "', '" + description + "', " + bankMap.get(bank_name) + ", '" + emailComboBox.getSelectedItem() + "')");
                JOptionPane.showMessageDialog(this, "Bank details added successfully.");
            } else {

                int response = JOptionPane.showConfirmDialog(this,
                        "Are you sure you want to update the bank details?",
                        "Confirm Update",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.YES_OPTION) {
                    DatabaseConnection.executeIUD("UPDATE `bank_details` SET `name` = '" + name + "', `acnumber` = '" + acnumber + "', `branch` = '" + branch + "', `description` = '" + description + "', `bank_id` = " + bankMap.get(bank_name) + " WHERE `employee_email` = '" + emailComboBox.getSelectedItem() + "'");
                    JOptionPane.showMessageDialog(this, "Bank details updated successfully.");
                } else {
                    JOptionPane.showMessageDialog(this, "Update canceled.");
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void checkBankDetails(String recent) {

        try {

            ResultSet bankresultSet = DatabaseConnection.executeSearch("SELECT * FROM `bank_details` "
                    + "INNER JOIN `bank` ON `bank_details`.`bank_id` = `bank`.`id` "
                    + "WHERE `bank_details`.`employee_email` = '" + emailComboBox.getSelectedItem() + "'");

            if (bankresultSet.next()) {
                if (recent.equals("view")) {
                    jTextField1.setText(bankresultSet.getString("name"));
                    jTextField2.setText(bankresultSet.getString("acnumber"));
                    jTextField3.setText(bankresultSet.getString("branch"));
                    jTextArea1.setText(bankresultSet.getString("description"));

                    bankComboBox.setSelectedItem(bankresultSet.getString("bank_name"));

                    addButton.setVisible(false);
                    addmoreButton.setVisible(false);
                    updateButton.setVisible(false);
                    cancelButton.setVisible(true);

                    emailComboBox.setEditable(false);
                    bankComboBox.setEditable(false);
                    jTextField1.setEditable(false);
                    jTextField2.setEditable(false);
                    jTextField3.setEditable(false);
                    jTextArea1.setEditable(false);
                } else {
                    jTextField1.setText(bankresultSet.getString("name"));
                    jTextField2.setText(bankresultSet.getString("acnumber"));
                    jTextField3.setText(bankresultSet.getString("branch"));
                    jTextArea1.setText(bankresultSet.getString("description"));

                    bankComboBox.setSelectedItem(bankresultSet.getString("bank_name"));

                    addButton.setVisible(false);
                    addmoreButton.setVisible(false);
                    updateButton.setVisible(true);
                    cancelButton.setVisible(true);
                }
            } else {
                if (recent.equals("view")) {
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextArea1.setText("");

                    bankComboBox.setSelectedIndex(0);

                    addButton.setVisible(false);
                    addmoreButton.setVisible(false);
                    updateButton.setVisible(false);
                    cancelButton.setVisible(true);
                } else {
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextArea1.setText("");

                    bankComboBox.setSelectedIndex(0);

                    addButton.setVisible(true);
                    addmoreButton.setVisible(true);
                    updateButton.setVisible(false);
                    cancelButton.setVisible(true);
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrUpdateBankAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrUpdateBankAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrUpdateBankAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrUpdateBankAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddOrUpdateBankAC dialog = new AddOrUpdateBankAC(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addmoreButton;
    private javax.swing.JComboBox<String> bankComboBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> emailComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
